### ISSUE TITLE
Unable to get routing to work

### ISSUE THREAD

**Issue by meAnurag** [horizon-ui/horizon-ui-chakra#10]
Hi there,
 I just installed this template and started to implement routing according to my needs. But I was unable to figure what would be the correct way to allow only singed in user to access certain routes without modifying much of preset routing mechanism.

**Comment by simmmpleweb** [comment]
Hello, @meAnurag ! Thanks for using our products ! 
I think you can find a good example [here](https://appseed.us/product/horizon-ui/api-server-nodejs/) .  @app-generator is one of our collaborators with whom we made backend versions for Horizon UI .
Regards, Vlad.
