### ISSUE TITLE
Color scheme mismatch

### ISSUE THREAD

**Issue by misrasaurabh1** [horizon-ui/horizon-ui-chakra#11]
Color Palette defined at https://github.com/horizon-ui/horizon-ui-chakra/blob/main/src/theme/styles.js differs from the documentation at https://horizon-ui.com/documentation/docs/theming/theme#gray
For example gray.100 in code is "#FAFCFE" whereas in documentation, it is "#EDF2F7". This leads to designs going off sync. I believe there are other examples of mismatch too.

**Comment by simmmpleweb** [comment]
Hello, @misrasaurabh1 ! Thanks for using our products! I changed the gray.100, I'm going to let this issue open if there are anymore theming problems. Regards, Vlad.
