### ISSUE TITLE
How to do /admin/xx/xx

### ISSUE THREAD

**Issue by Ryan0204** [horizon-ui/horizon-ui-chakra#14]
How can i add sub url 
now only /admin/xx

**Comment by simmmpleweb** [comment]
Hello, @Ryan0204 ! Thanks for using our products !

1. Go in `/src/index.tsx` and change `<Route path={'/admin'}>` to your liking
2. In `/src/layouts/**' change the `getRoutes`, `getActiveRoutes`, and` getActiveNavbar` so they use your path.
3. In `/src/routes.tsx` , add your pages while using your own paths for `layout `and `path` props.

I hope it helps! Regards, Vlad.
