### ISSUE TITLE
Not seeing TimelineRow in code

### ISSUE THREAD

**Issue by sudeepy** [horizon-ui/horizon-ui-chakra#15]
Hi, the docs mention a TimelineRow component (https://horizon-ui.com/documentation/docs/data-display/timeline), but I can't find it in the code. Please advise.

**Comment by simmmpleweb** [comment]
Hello, @sudeepy ! Thanks for using our products! For the moment, the TimelineRow component is not in the code for some technical reasons, but we will re-add it soon! Regards, Vlad.

**Comment by sudeepy** [comment]
Hi Vlad, any ETA on this? It's deceiving to list a component in your documentation but not have it available.

**Comment by simmmpleweb** [comment]
Hello, @sudeepy ! We added the TimelineRow to the `dataDisplay` folder and now you should be able to use it. Cheers!

**Comment by sudeepy** [comment]
Great, thank you!
