### ISSUE TITLE
Request: update to @tanstack/react-table v8

### ISSUE THREAD

**Issue by mfferreira** [horizon-ui/horizon-ui-chakra#18]
Is this in the roadmap?

**Comment by simmmpleweb** [comment]
Hello, @mfferreira ! Thanks for using our products. This will probably come in 2 updates from now on. However, we already implemented v8 tables in the [Typescript Version](https://github.com/horizon-ui/horizon-ui-chakra-ts/tree/feature/react-table-v8).

**Comment by mfferreira** [comment]
> Hello, @mfferreira ! Thanks for using our products. This will probably come in 2 updates from now on. However, we already implemented v8 tables in the [Typescript Version](https://github.com/horizon-ui/horizon-ui-chakra-ts/tree/feature/react-table-v8).

That's great! Thanks for the great ui lib.
