### ISSUE TITLE
building and serving dashboard

### ISSUE THREAD

**Issue by LexxLuey** [horizon-ui/horizon-ui-chakra#20]
`yarn build`
This created the per usual React App optimized for the deployment.
But on serving it, it was blank and rendered nothing:
![image](https://user-images.githubusercontent.com/71068965/204824548-9a87562f-ec92-4012-bda4-f63b15ae93db.png)

And nowhere in your docs is build instruction explained. What do we do?

OS: Ubuntu 22

**Comment by dinxsh** [comment]
@simmmpleweb, facing the same issue even after removing "homepage" from package.json. hosted on vercel. kindly help me here.

**Comment by simmmpleweb** [comment]
Do you have any errors? My version works perfectly fine, we have all live previews deployed by vercel as well.

**Comment by dinxsh** [comment]
plain white screen on route "#/admin/" is displayed 
![image](https://user-images.githubusercontent.com/90450035/227680357-beaaf6be-99b5-4039-83b4-2010b6860fbb.png)

**Comment by dinxsh** [comment]
@simmmpleweb fixed, was an eslint issue, mb :,)
