### ISSUE TITLE
remove # from route

### ISSUE THREAD

**Issue by dinxsh** [horizon-ui/horizon-ui-chakra#26]
![image](https://user-images.githubusercontent.com/90450035/234920313-ca5f37b3-8161-4e22-91a1-56782d10b914.png)

how do I remove the # from the route (like displayed in above image) such that it's `http://localhost:3000/auth/default`

**Comment by Bravco** [comment]
To remove the "#" from the route in your React application, you can use the `BrowserRouter` component provided by the React Router library. 

Here's an example of how you can use it:

1. First, make sure that you have installed React Router in your project by running the following command:

   ```
   npm install react-router-dom
   ```

2. Import the `BrowserRouter` component in your main app component:

   ```javascript
   import { BrowserRouter } from 'react-router-dom';
   ```

3. Wrap your entire application inside the `BrowserRouter` component:

   ```javascript
   import { BrowserRouter } from 'react-router-dom';

   function App() {
     return (
       <BrowserRouter>
         {/* your app content goes here */}
       </BrowserRouter>
     );
   }

   export default App;
   ```

4. Use the `Link` component from React Router to create links to other pages in your application:

   ```javascript
   import { Link } from 'react-router-dom';

   function MyComponent() {
     return (
       <Link to="/auth/default">Go to default page</Link>
     );
   }
   ```

   When the link is clicked, the URL in the browser address bar will change to `http://localhost:3000/auth/default`.

With these steps, you should now have a React application with clean, readable URLs without the "#" symbol.

**Comment by dinxsh** [comment]
@Bravco have these on nearly all the routes (in layouts folder). yet # is a route!
```
<Switch>
                {getRoutes(routes)}
                <Redirect from='/' to='/admin/default' />
</Switch>
```
