### ISSUE TITLE
react-router-dom params integration into routing component

### ISSUE THREAD

**Issue by riccardogiuriola** [horizon-ui/horizon-ui-chakra#29]
Hi, would it be possible to add params routing in the project?
For example if i navigate to /admin/users/:userId.

If so is there an easy solution before i start to dismantle the code?

Thank you.

**Comment by simmmpleweb** [comment]
Hello, @riccardogiuriola ! Thank you for supporting Horizon! You can easily change the routing in the layout files in `src/layout` . Don't forget to change the routing in the Sidebar as well according to your changes in layouts.
