### ISSUE TITLE
Set Dark Them by default

### ISSUE THREAD

**Issue by theejkb** [horizon-ui/horizon-ui-chakra#3]
Hey everyone,
I like your template horizon-ui-pro.
I need to set by default dark them (and also remove this feature to only get dark them).
But I'm stuck. Could you help me?

**Comment by simmmpleweb** [comment]
Hi, @theejkb  ! Thanks for using our products. Here is an in depth guide on how to set your theme to whatever mode you like: https://chakra-ui.com/docs/styled-system/features/color-mode. When referring to App.js, you should look for our layout components. Regards, Vlad.
