### ISSUE TITLE
horizon UI header section content getting overlapped

### ISSUE THREAD

**Issue by kuntal0901** [horizon-ui/horizon-ui-chakra#32]
**The issue**
In the screenshot you can see that the horizon UI header has admin template being overlapped over components.

**The system configurations :** 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

**The screenshot:**
<img width="960" alt="Screenshot 2023-10-26 100018" src="https://github.com/horizon-ui/horizon-ui-chakra/assets/54110827/27529204-fdfa-4885-a57b-fe21a354ae63">

**Comment by simmmpleweb** [comment]
Hello, @kuntal0901 ! Can you please tell us the size of your screen in px?
Regards, Vlad.

**Comment by simmmpleweb** [comment]
Closed since it does not regard the produs + no info was provided.
