### ISSUE TITLE
Upgrade react router to v6

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [horizon-ui/horizon-ui-chakra#35]

**Comment by simmmpleweb** [comment]
Hello, @mariomurrent-softwaresolutions ! I will close the issue for now, we are planning to do the update soon enough! I will return to this issue and ping you when it's done.
Regards, Vlad.

**Comment by mariomurrent-softwaresolutions** [comment]
Sounds great. Thank you very much 😊 love your template, keep up the awesome work
