### ISSUE TITLE
OpenAI API Key Exposed in HTML on /dashboard/ai-assistant

### ISSUE THREAD

**Issue by ImmanEb** [horizon-ui/horizon-ui-chakra#45]
Hello,

I have noticed a critical security issue in the Horizon UI Chakra project. On the /dashboard/ai-assistant page, the OpenAI API key is exposed in the HTML as the value for the key apiKeyApp. This exposure can lead to unauthorized use of the API key and potential security breaches.

Steps to reproduce:

1. Navigate to the /dashboard/ai-assistant page.
2. Inspect the HTML source code.
3. Find the apiKeyApp key, which contains the OpenAI API key as its value.

This issue needs immediate attention to secure the API key and protect sensitive information.

Thank you.

**Comment by simmmpleweb** [comment]
Hello, @ImmanEb ! It's fixed, I will ping you when it is up, and I will also close the issue then.
Vlad.

**Comment by simmmpleweb** [comment]
To problem has been fixed on every version of our product that presented the issue. @ImmanEb
