### ISSUE TITLE
Warnings / Errors in the JS Console

### ISSUE THREAD

**Issue by app-generator** [horizon-ui/horizon-ui-chakra#9]
All pages bump JS errors/warnings in the browser console.

![horizon-free-js-console-errors](https://user-images.githubusercontent.com/51070104/171789817-0fd8c93a-f5e5-49be-bd27-638725aedf2d.gif)

**Comment by simmmpleweb** [comment]
Hello, @app-generator ! Thanks for using our products! We just fixed the problem ! Regards, Vlad.
